# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64beaf6ba5abe155a3c2c4d973676b116e8eb5e0dba4c2e9195a94a5b405bda752d681fc74365daf133478812922933b17f4a368a1334e03494973d6cd420416

test:
  secret_key_base: 7fec574355f0b5ddb39241b44b7ea1a72e4380979cb46cb6972caa5064c85d690bf991cc7d621e9920d4c3930a74a5091939be2c1178b2fcef6ccd2b6b0a0881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
